language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=postgresql
before_script:
  - psql -c 'create database uplay_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
